### ISSUE TITLE
Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by miyasudokoro** [wessberg/cjstoesm#25]
The following file content throws `TypeError: Cannot read property 'text' of undefined at transformSourceFile ([redacted]\node_modules\cjstoesm\dist\cli\index.js:3019:61)`

```
function myFunction() {
    console.log( 'lorem ipsum' );
}

module.exports = {
    myFunction
};
```

**Comment by icebob** [comment]
Same issue here. 
```
(node:18380) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'text' of undefined
    at transformSourceFile (D:\Work\moleculer\moleculer\node_modules\cjstoesm\dist\cli\index.js:3019:61)
    at D:\Work\moleculer\moleculer\node_modules\cjstoesm\dist\cli\index.js:3069:30
    at transformSourceFileOrBundle (D:\Work\moleculer\moleculer\node_modules\typescript\lib\typescript.js:88330:57)
    at transformation (D:\Work\moleculer\moleculer\node_modules\typescript\lib\typescript.js:107031:24)
    at transformRoot (D:\Work\moleculer\moleculer\node_modules\typescript\lib\typescript.js:107058:82)
    at Object.transformNodes (D:\Work\moleculer\moleculer\node_modules\typescript\lib\typescript.js:107042:78)
    at emitJsFileOrBundle (D:\Work\moleculer\moleculer\node_modules\typescript\lib\typescript.js:107709:32)
    at emitSourceFileOrBundle (D:\Work\moleculer\moleculer\node_modules\typescript\lib\typescript.js:107656:13)
    at forEachEmittedFile (D:\Work\moleculer\moleculer\node_modules\typescript\lib\typescript.js:107395:34)
    at Object.emitFiles (D:\Work\moleculer\moleculer\node_modules\typescript\lib\typescript.js:107636:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:18380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by sheltonsuen** [comment]
same issue with
```javascript
const foo = 'foo';
module.exports = {
  foo
}
```

**Comment by jialinhome** [comment]
same issue width
`var Graph = require("./lib/graphlib").Graph;
module.exports = {
  layout: Graph,
};`

**Comment by StefanRetief** [comment]
changing to typescript version 4.3.2 fixed it for me.

**Comment by Kreijstal** [comment]
same issue here

**Comment by uooq** [comment]
typescript 4.3.2 solves it for me

**Comment by TheBrenny** [comment]
In your console:
```console
$ npm install typescript@4.3.2
```

then in your code where you `cjstoesm`:
```js
await cjstoesm({
    input: "src/**/*.*",
    outDir: "dist",
    typescript: require("typescript")
});
```

**Comment by wessberg** [comment]
Hi there. I can't seem to reproduce this behavior, even with the test case I've written for it.
Which TypeScript version were you using when you experienced this behavior? Is it reproducible with [v1.1.5](https://github.com/wessberg/cjstoesm/releases/tag/v1.1.5) of `cjstoesm`?

**Comment by wessberg** [comment]
Now that [v2.0.0](https://github.com/wessberg/cjstoesm/releases/tag/v2.0.0) is out, I'm closing this issue, as I haven't been able to reproduce this issue with any TypeScript version. However, if the problem persist, please write a comment with a repro, and I'll be glad to investigate further and potentially reopen this issue.
